name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 195.35.39.203 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 195.35.39.203
          REMOTE_USER: u179764972
          REMOTE_PORT: 65002
        with:
          source: "."
          target: "/home/u179764972/public_html"
          args: "-rltgoDzvO --verbose"
