name: Deploy to Server

on:
  push:
    branches:
      - main # Adjust this branch name as per your requirements

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to the server
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT || 22 }}
        with:
          source: "." # Directory to deploy (current directory in this case)
          target: "/home/u179764972/public_html" # Replace with the target directory on your server
          args: "-rltgoDzvO" # Additional rsync options (optional)
